update from goldorak

diff --git a/bin/kubetail b/bin/kubetail
--- a/bin/kubetail
+++ b/bin/kubetail
@@ -1,29 +1,28 @@
 #!/usr/bin/env bash
 
-set -o nounset
 set -o errexit
 set -o pipefail
 
 if [ -z "${KUBECTL_BIN}" ]; then
-	if hash kubectl 2>/dev/null; then
-		KUBECTL_BIN='kubectl'
-	elif hash kubectl.exe 2>/dev/null; then
-		KUBECTL_BIN='kubectl.exe'
-	elif hash microk8s 2>/dev/null; then
-		KUBECTL_BIN='microk8s.kubectl'
-	fi
+    if hash kubectl 2>/dev/null; then
+        KUBECTL_BIN='kubectl'
+    elif hash kubectl.exe 2>/dev/null; then
+        KUBECTL_BIN='kubectl.exe'
+    elif hash microk8s 2>/dev/null; then
+        KUBECTL_BIN='microk8s.kubectl'
+    fi
 fi
 
 if ! hash "${KUBECTL_BIN}" 2>/dev/null; then
-	echo >&2 "kubectl is not installed"
-	exit 1
+    echo >&2 "kubectl is not installed"
+    exit 1
 fi
 
 readonly PROGNAME=$(basename $0)
 
 calculate_default_namespace() {
-	local config_namespace=$(${KUBECTL_BIN} config view --minify --output 'jsonpath={..namespace}')
-	echo "${KUBETAIL_NAMESPACE:-${config_namespace:-default}}"
+    local config_namespace=$(${KUBECTL_BIN} config view --minify --output 'jsonpath={..namespace}')
+    echo "${KUBETAIL_NAMESPACE:-${config_namespace:-default}}"
 }
 
 # Sets default color ouput to 'false' if output is not a terminal
@@ -57,9 +56,8 @@ skip_colors="${default_skip_colors}"
 tail="${default_tail}"
 show_color_index="${default_show_color_index}"
 
-if [[ ${1} != -* ]]
-then
-	pod="${1}"
+if [[ ${1} != -* ]]; then
+    pod="${1}"
 fi
 containers=()
 selector=()
@@ -117,199 +115,196 @@ examples:
     ${PROGNAME} --tail 1"
 
 if [ "$#" -ne 0 ]; then
-	while [ "$#" -gt 0 ]
-	do
-		case "$1" in
-		-h|--help)
-			echo "$usage"
-			exit 0
-			;;
-		-v|--version)
-			echo "$version"
-			exit 0
-			;;
-		-c|--container)
-			containers+=("$2")
-			;;
-		-e|--regex)
-			if [ "$2" = "substring" ]; then
-				regex="substring"
-			else
-				regex="regex"
-			fi
-			;;
-		-t|--context)
-			context="$2"
-			;;
-		-r|--cluster)
-			cluster="--cluster $2"
-			;;
-		-l|--selector)
-			selector=(--selector "$2")
-			pod=""
-			;;
-		-d|--dry-run)
-			dryrun=true
-			;;
-		-p|--previous)
-			if [ "$2" = "false" ]; then
-				previous="false"
-			else
-				previous="true"
-			fi
-			;;
-		-s|--since)
-			if [ -z "$2" ]; then
-				since="${default_since}"
-			else
-				since="$2"
-			fi
-			;;
-		-n|--namespace)
-			if [ -z "$2" ]; then
-				# using namespace from context
-				:
-			else
-				namespace_arg="--namespace $2"
-			fi
-			;;
-		-f|--follow)
-			if [ "$2" = "false" ]; then
-				follow="false"
-			else
-				follow="true"
-			fi
-			;;
-		-P|--prefix)
-			if [ "$2" = "false" ]; then
-				prefix="false"
-			else
-				prefix="true"
-			fi
-			;;
-		-b|--line-buffered)
-			if [ "$2" = "false" ]; then
-				line_buffered="false"
-			else
-				line_buffered="$2"
-			fi
-			;;
-		-k|--colored-output)
-			if [ -z "$2" ]; then
-				colored_output="${default_colored_output}"
-			else
-				colored_output="$2"
-			fi
-			;;
-		-j|--jq)
-			if [ -z "$2" ]; then
-				jq_selector="${default_jq_selector}"
-			else
-				jq_selector="$2"
-			fi
-			;;
-		-z|--skip-colors)
-			if [ -z "$2" ]; then
-				skip_colors="${default_skip_colors}"
-			else
-				skip_colors="$2"
-			fi
-			;;
-		--timestamps)
-			if [ "$2" = "false" ]; then
-					timestamps="$1=$2"
-			else
-					timestamps="$1"
-			fi
-			;;
-		--tail)
-			if [ -z "$2" ]; then
-					tail="${default_tail}"
-			else
-					tail="$2"
-			fi
-			;;
-		-i|--show-color-index)
-			if [ -z "$2" ]; then
-					show_color_index="${default_show_color_index}"
-			else
-					show_color_index="$2"
-			fi
-			;;
-		--)
-			break
-			;;
-		-*)
-			echo "Invalid option '$1'. Use --help to see the valid options" >&2
-			exit 1
-			;;
-		# an option argument, continue
-		*) ;;
-		esac
-		shift
-	done
+    while [ "$#" -gt 0 ]; do
+        case "$1" in
+            -h | --help)
+                echo "$usage"
+                exit 0
+                ;;
+            -v | --version)
+                echo "$version"
+                exit 0
+                ;;
+            -c | --container)
+                containers+=("$2")
+                ;;
+            -e | --regex)
+                if [ "$2" = "substring" ]; then
+                    regex="substring"
+                else
+                    regex="regex"
+                fi
+                ;;
+            -t | --context)
+                context="$2"
+                ;;
+            -r | --cluster)
+                cluster="--cluster $2"
+                ;;
+            -l | --selector)
+                selector=(--selector "$2")
+                pod=""
+                ;;
+            -d | --dry-run)
+                dryrun=true
+                ;;
+            -p | --previous)
+                if [ "$2" = "false" ]; then
+                    previous="false"
+                else
+                    previous="true"
+                fi
+                ;;
+            -s | --since)
+                if [ -z "$2" ]; then
+                    since="${default_since}"
+                else
+                    since="$2"
+                fi
+                ;;
+            -n | --namespace)
+                if [ -z "$2" ]; then
+                    # using namespace from context
+                    :
+                else
+                    namespace_arg="--namespace $2"
+                fi
+                ;;
+            -f | --follow)
+                if [ "$2" = "false" ]; then
+                    follow="false"
+                else
+                    follow="true"
+                fi
+                ;;
+            -P | --prefix)
+                if [ "$2" = "false" ]; then
+                    prefix="false"
+                else
+                    prefix="true"
+                fi
+                ;;
+            -b | --line-buffered)
+                if [ "$2" = "false" ]; then
+                    line_buffered="false"
+                else
+                    line_buffered="$2"
+                fi
+                ;;
+            -k | --colored-output)
+                if [ -z "$2" ]; then
+                    colored_output="${default_colored_output}"
+                else
+                    colored_output="$2"
+                fi
+                ;;
+            -j | --jq)
+                if [ -z "$2" ]; then
+                    jq_selector="${default_jq_selector}"
+                else
+                    jq_selector="$2"
+                fi
+                ;;
+            -z | --skip-colors)
+                if [ -z "$2" ]; then
+                    skip_colors="${default_skip_colors}"
+                else
+                    skip_colors="$2"
+                fi
+                ;;
+            --timestamps)
+                if [ "$2" = "false" ]; then
+                    timestamps="$1=$2"
+                else
+                    timestamps="$1"
+                fi
+                ;;
+            --tail)
+                if [ -z "$2" ]; then
+                    tail="${default_tail}"
+                else
+                    tail="$2"
+                fi
+                ;;
+            -i | --show-color-index)
+                if [ -z "$2" ]; then
+                    show_color_index="${default_show_color_index}"
+                else
+                    show_color_index="$2"
+                fi
+                ;;
+            --)
+                break
+                ;;
+            -*)
+                echo "Invalid option '$1'. Use --help to see the valid options" >&2
+                exit 1
+                ;;
+            # an option argument, continue
+            *) ;;
+        esac
+        shift
+    done
 else
-	echo "$usage"
-	exit 1
+    echo "$usage"
+    exit 1
 fi
 
 # Validate colored_output option
 if [ "$colored_output" != "pod" ] && [ "$colored_output" != "line" ] && [ "$colored_output" != "loglevel" ] && [ "$colored_output" != "false" ]; then
-	echo "Invalid colored output option: $colored_output. Valid options are: pod, line, loglevel, false"
-	exit 1
+    echo "Invalid colored output option: $colored_output. Valid options are: pod, line, loglevel, false"
+    exit 1
 fi
 
 # Join function that supports a multi-character separator (copied from http://stackoverflow.com/a/23673883/398441)
 function join() {
-	# $1 is sep
-	# $2... are the elements to join
-	local sep="$1"
-	shift
+    # $1 is sep
+    # $2... are the elements to join
+    local sep="$1"
+    shift
 
-	local F=0
-	for x in "$@"
-	do
-		if [[ F -eq 1 ]]
-			then
-				echo -n "$sep"
-			else
-				F=1
-			fi
-			echo -n "$x"
-	done
-	echo
+    local F=0
+    for x in "$@"; do
+        if [[ F -eq 1 ]]; then
+            echo -n "$sep"
+        else
+            F=1
+        fi
+        echo -n "$x"
+    done
+    echo
 }
 
 # Check if pod query contains a comma and we've not specified "regex" explicitly,
 # if so we convert the pod query string into a regex that matches all pods seperated by the comma
 if [[ "${pod}" = *","* ]] && [ ! "${regex}" == 'regex' ]; then
 
-	# Split the supplied query string (in variable pod) by comma into an array named "pods_to_match"
-	IFS=',' read -r -a pods_to_match <<< "${pod}"
+    # Split the supplied query string (in variable pod) by comma into an array named "pods_to_match"
+    IFS=',' read -r -a pods_to_match <<<"${pod}"
 
-	# Join all pod names into a string with ".*|.*" as delimiter
-	pod=$(join ".*|.*" "${pods_to_match[@]}")
+    # Join all pod names into a string with ".*|.*" as delimiter
+    pod=$(join ".*|.*" "${pods_to_match[@]}")
 
-	# Prepend and initial ".*" and and append the last ".*"
-	pod=".*${pod}.*"
+    # Prepend and initial ".*" and and append the last ".*"
+    pod=".*${pod}.*"
 
-	# Force the use of regex matching
-	regex='regex'
+    # Force the use of regex matching
+    regex='regex'
 fi
 
 grep_matcher=''
 if [ "${regex}" == 'regex' ]; then
-	echo "Using regex '${pod}' to match pods"
-	grep_matcher='-E'
+    echo "Using regex '${pod}' to match pods"
+    grep_matcher='-E'
 fi
 
 # Get all pods matching the input and put them in an array. If no input then all pods are matched.
-matching_pods=(`${KUBECTL_BIN} get pods ${context:+--context=${context}} "${selector[@]}" ${namespace_arg} ${cluster} --field-selector=status.phase=Running --output=jsonpath='{.items[*].metadata.name}' | xargs -n1 | grep --color=never $grep_matcher "${pod}"`)
+matching_pods=($(${KUBECTL_BIN} get pods ${context:+--context=${context}} "${selector[@]}" ${namespace_arg} ${cluster} --field-selector=status.phase=Running --output=jsonpath='{.items[*].metadata.name}' | xargs -n1 | grep --color=never $grep_matcher "${pod}"))
 matching_pods_size=${#matching_pods[@]}
 
 if [ ${matching_pods_size} -eq 0 ]; then
-	echo "No pod exists that matches ${pod}"
-	exit 1
+    echo "No pod exists that matches ${pod}"
+    exit 1
 fi
 
 color_end=$(tput sgr0)
@@ -321,18 +316,18 @@ i=0
 color_index=0
 
 function next_col {
-	potential_col=$(($1+1))
-	[[ $skip_colors =~ (^|,)$potential_col($|,) ]] && echo `next_col $potential_col` || echo $potential_col
+    potential_col=$(($1 + 1))
+    [[ $skip_colors =~ (^|,)$potential_col($|,) ]] && echo $(next_col $potential_col) || echo $potential_col
 }
 
 # Allows for more colors, this is useful if one tails a lot pods
 if [ ${colored_output} != "false" ]; then
-	export TERM=xterm-256color
+    export TERM=xterm-256color
 fi
 
 # Function that kills all kubectl processes that are started by kubetail in the background
 function kill_kubectl_processes {
-	kill 0
+    kill 0
 }
 
 # Invoke the "kill_kubectl_processes" function when the script is stopped (including ctrl+c)
@@ -341,61 +336,60 @@ function kill_kubectl_processes {
 trap kill_kubectl_processes EXIT
 
 # Putting all needed values in a variable so that multiple requests to Kubernetes api can be avoided, thus making it faster
-all_pods_containers=$(echo -e `${KUBECTL_BIN} get pods ${namespace_arg} ${context:+--context=${context}} --output=jsonpath="{range .items[*]}{.metadata.name} {.spec['containers', 'initContainers'][*].name} \n{end}"`)
-
+all_pods_containers=$(echo -e $(${KUBECTL_BIN} get pods ${namespace_arg} ${context:+--context=${context}} --output=jsonpath="{range .items[*]}{.metadata.name} {.spec['containers', 'initContainers'][*].name} \n{end}"))
 
 for pod in "${matching_pods[@]}"; do
-	if [ ${#containers[@]} -eq 0 ]; then
-		pod_containers=($(echo -e "$all_pods_containers" | grep "$pod " | cut -d ' ' -f2- | xargs -n1))
-	else
-		pod_containers=("${containers[@]}")
-	fi
+    if [ ${#containers[@]} -eq 0 ]; then
+        pod_containers=($(echo -e "$all_pods_containers" | grep "$pod " | cut -d ' ' -f2- | xargs -n1))
+    else
+        pod_containers=("${containers[@]}")
+    fi
 
-	for container in "${pod_containers[@]}"; do
-		[ ${matching_pods_size} -eq 1 -a ${#pod_containers[@]} -eq 1 ] && single_stream="true" || single_stream="false"
+    for container in "${pod_containers[@]}"; do
+        [ ${matching_pods_size} -eq 1 -a ${#pod_containers[@]} -eq 1 ] && single_stream="true" || single_stream="false"
 
-		if [ ${colored_output} == "false" ] || [ ${single_stream} == "true" ]; then
-			color_start=$(tput sgr0)
-			color_index_prefix=""
-		else
-			color_index=`next_col $color_index`
-			color_start=$(tput setaf $color_index)
-			color_index_prefix=`if [ ${show_color_index} == "true" ]; then echo "${color_index}:"; else echo ""; fi`
-		fi
+        if [ ${colored_output} == "false" ] || [ ${single_stream} == "true" ]; then
+            color_start=$(tput sgr0)
+            color_index_prefix=""
+        else
+            color_index=$(next_col $color_index)
+            color_start=$(tput setaf $color_index)
+            color_index_prefix=$(if [ ${show_color_index} == "true" ]; then echo "${color_index}:"; else echo ""; fi)
+        fi
 
-		if [ ${#pod_containers[@]} -eq 1 ]; then
-			display_name="${pod}"
-		else
-			display_name="${pod} ${container}"
-		fi
+        if [ ${#pod_containers[@]} -eq 1 ]; then
+            display_name="${pod}"
+        else
+            display_name="${pod} ${container}"
+        fi
 
-		if [ ${colored_output} == "false" ]; then
-			display_names_preview+=("${display_name}")
-		else
-			display_names_preview+=("$color_index_prefix${color_start}${display_name}${color_end}")
-		fi
+        if [ ${colored_output} == "false" ]; then
+            display_names_preview+=("${display_name}")
+        else
+            display_names_preview+=("$color_index_prefix${color_start}${display_name}${color_end}")
+        fi
 
-		if [ ${prefix} == "false" ]; then
-			prefix_line=""
-		else
-			if [ ${colored_output} == "false" ]; then
-				prefix_line="[${display_name}] "
-			else
-				prefix_line="${color_start}[${color_end}${color_index_prefix}${color_start}${display_name}]${color_end} "
-			fi
-		fi
+        if [ ${prefix} == "false" ]; then
+            prefix_line=""
+        else
+            if [ ${colored_output} == "false" ]; then
+                prefix_line="[${display_name}] "
+            else
+                prefix_line="${color_start}[${color_end}${color_index_prefix}${color_start}${display_name}]${color_end} "
+            fi
+        fi
 
-		if [ ${colored_output} == "false" ] || [ ${colored_output} == "pod" ]; then
-			colored_line="${prefix_line}\$REPLY"
-		else
-			colored_line="${prefix_line}${color_start}\$REPLY${color_end}"
-		fi
+        if [ ${colored_output} == "false" ] || [ ${colored_output} == "pod" ]; then
+            colored_line="${prefix_line}\$REPLY"
+        else
+            colored_line="${prefix_line}${color_start}\$REPLY${color_end}"
+        fi
 
-		kubectl_cmd="${KUBECTL_BIN} ${context:+--context=${context}} logs ${pod} ${container} -f=${follow} --previous=${previous} --since=${since} --tail=${tail} ${namespace_arg} ${cluster}"
+        kubectl_cmd="${KUBECTL_BIN} ${context:+--context=${context}} logs ${pod} ${container} -f=${follow} --previous=${previous} --since=${since} --tail=${tail} ${namespace_arg} ${cluster}"
 
-		if [ ${colored_output} == "loglevel" ]; then
-			# Log level based coloring with colored pod names
-			colorify_lines_cmd="while read -r; do
+        if [ ${colored_output} == "loglevel" ]; then
+            # Log level based coloring with colored pod names
+            colorify_lines_cmd="while read -r; do
 				# Create colored prefix similar to pod mode
 				colored_prefix=\"${color_start}[${color_end}${color_index_prefix}${color_start}${display_name}]${color_end} \"
 
@@ -418,32 +412,31 @@ for pod in "${matching_pods[@]}"; do
 				fi
 				echo \"\$colored_line\" | tail -n +1
 			done"
-		else
-			# Original coloring logic for pod/line/false modes
-			colorify_lines_cmd="while read -r; do
+        else
+            # Original coloring logic for pod/line/false modes
+            colorify_lines_cmd="while read -r; do
 				echo \"$colored_line\" | tail -n +1
 			done"
-		fi
-		if [ "z" == "z$jq_selector" ]; then
-			logs_commands+=("${kubectl_cmd} ${timestamps} | ${colorify_lines_cmd}");
-		else
-			logs_commands+=("${kubectl_cmd} | jq --unbuffered -r -R --stream '. as \$line | try (fromjson | $jq_selector) catch \$line' | ${colorify_lines_cmd}");
-		fi
+        fi
+        if [ "z" == "z$jq_selector" ]; then
+            logs_commands+=("${kubectl_cmd} ${timestamps} | ${colorify_lines_cmd}")
+        else
+            logs_commands+=("${kubectl_cmd} | jq --unbuffered -r -R --stream '. as \$line | try (fromjson | $jq_selector) catch \$line' | ${colorify_lines_cmd}")
+        fi
 
-		# There are only 11 usable colors
-		i=$(( ($i+1)%13 ))
-	done
+        # There are only 11 usable colors
+        i=$((($i + 1) % 13))
+    done
 done
 
 # Preview pod colors
 echo "Will tail ${#display_names_preview[@]} logs..."
 for preview in "${display_names_preview[@]}"; do
-	echo "$preview"
+    echo "$preview"
 done
 
-if [[ ${dryrun} == true ]];
-then
-	exit 0
+if [[ ${dryrun} == true ]]; then
+    exit 0
 fi
 
 # Join all log commands into one string separated by " & "
@@ -453,21 +446,19 @@ command_to_tail=$(join " & " "${logs_commands[@]}")
 # Note that tail +1f doesn't work on some Linux distributions so we use this slightly longer alternative
 # Note that if --follow=false, then the tail command should also not be followed
 tail_follow_command="-f"
-if [[ ${follow} == false ]];
-then
-	tail_follow_command=""
+if [[ ${follow} == false ]]; then
+    tail_follow_command=""
 fi
-
 
 command_to_run="tail ${tail_follow_command} -n +1 <( eval "${command_to_tail}" )"
 
 if [ "${line_buffered}" == "false" ]; then
-	distro="$(uname)"
-	if [[ "$distro" == "Darwin" || "$distro" == "FreeBSD" ]]; then
-	    command_to_run="script -q /dev/null ${command_to_run}"
-	else # Linux etc
-	    command_to_run="script -q -c '${command_to_run}' /dev/null"
-	fi
+    distro="$(uname)"
+    if [[ "$distro" == "Darwin" || "$distro" == "FreeBSD" ]]; then
+        command_to_run="script -q /dev/null ${command_to_run}"
+    else # Linux etc
+        command_to_run="script -q -c '${command_to_run}' /dev/null"
+    fi
 fi
 
 eval "${command_to_run}"
