setbg: big rewrite; update lock en i3 and minor i3 tweaks

diff --git a/bin/setbg b/bin/setbg
--- a/bin/setbg
+++ b/bin/setbg
@@ -1,97 +1,156 @@
-#! /bin/bash -e
+#!/bin/bash -e
 
-# File locations
+## Parameters
+
 tmp=/tmp/filelist.log
 defaultbg=$HOME/.background.png
 lockscreen_image=".lockscreen.png"
 pictures=Pictures/Backgrounds
-target=${1}
-action=${2}
 
-# check target
-if [ ! -z "${target}" -a ! -r "${target}" ]
-# if target not empty but not a readable path
-# assume subdir or path in home or just action
-then
-    if [ -r "$HOME/${pictures}/${target}" ]
-    then # subdir of pictures folder
-        target="$HOME/${pictures}/${target}"
-    elif [ -r "$HOME/${target}" ]
-    then # folder beneath home
-        target="$HOME/${target}"
-    else # maybe an action?
-        case ${target} in
-            i3lock|path)
-                action=${target}
-                target="${defaultbg}"
+p1="$1"
+p2="$2"
+
+
+## Functions
+
+error() {
+    echo "$*" >&2
+    exit 1
+}
+
+checkcli() {
+    # check cli parameters
+    if [ -z "$p1" ]     # zero parameters
+    then
+        action='default'
+        target="${defaultbg}"
+    elif [ ! -z "$p2" ] # two parameters
+    then
+        action="$p1"
+        target="$p2"
+    else                # only one parameter
+        case "$p1" in
+            ## keep this in sync with options in main loop
+            lock|redisplay|default)
+                action="$p1"
+                if [ ! -z "$p2" ] # two parameters
+                then
+                    target="${p2}"
+                else
+                    target="${defaultbg}"
+                fi
                 ;;
-            *) # unknown, error
-                echo ${target} is unknown >&2
-                exit 1
+            *)
+                action='default'
+                target="$p1"
                 ;;
         esac
     fi
-fi
+}
 
-if [ "${action}" = "i3lock" ]
-then
-    _search="-iregex .*.png"
-else
-    _search="-iregex .*.jpg -o -iregex .*.png"
-fi
+checktarget() {
+    ## check target
 
-if [ -z "${target}" ]
-then # if no parameters, just confirm default bg
-    background=${defaultbg}
-elif [ -d "${target}" ]
-then # if directory, the pick a random picture
-    pictures="${target}"
-    
-    # disable shell expansion for the iregex
-    set -o noglob 
-    # Create a temporary logfile of all matches
-    find -L ${pictures} $_search > ${tmp}
-    # reenable shell expansion
-    set +o noglob
-
-    # Choose a random line number (any number from 1 to the length of the file)
-    LowerBound=1
-    RandomMax=32767
-    UpperBound=$(cat ${tmp} | wc -l)
-    if [ $UpperBound -eq 0 ]
-    then
-        echo "No matching pictures found" >&2
-        exit 1
+    if [ -r "${target}" ]
+        then :
+    elif [ -r "$HOME/${pictures}/${target}" ]
+        then target="$HOME/${pictures}/${target}"
+    elif [ -r "$HOME/${target}" ]
+        then target="$HOME/${target}"
+    else
+        error "Cannot find a target \"${target}\""
     fi
-    RandomLine=$(( $LowerBound + ($UpperBound * $RANDOM) / ($RandomMax + 1) ))
+}
 
-    # Use sed to grab the random line
-    background=$(sed -n "$RandomLine{p;q;}" "${tmp}")
-elif [ -r "${target}" ]
-then # not a dir but readeable, should be a picture
-    background="${target}"
-else
-    echo Unexpected error, this should not happen >&2
-    exit 1
-fi
+pickpic() {
+    # get picture according to target
+    # target is set to a file/dir we can read
+    if [ -d "${target}" ]
+    then # if directory, the pick a random picture
+        pictures="${target}"
 
-# now we have a picture set for $background, let's do something with it
-if [ "${action}" = "i3lock" ]
-then    # create a picture fill-resized to the primary screen for the lockscreen
-    disp_res=`xrandr | grep primary | awk '{print $4}' | sed s/\+.*//g`
-    convert "${background}" -resize ${disp_res}^ -gravity center -extent ${disp_res} "${lockscreen_image}"
-elif [ "${action}" = "path" ]
-then    # just return the path later
-    :
-else    # set as background
-        # if same default, also resizes if new screen display
-        # this gets called from our xrandr script
-    [ ! "${background}" = "${defaultbg}" ] && (
-        background=`readlink -e "${background}"`
-        ln -nfs "${background}" "${defaultbg}")
+        # disable shell expansion for the iregex
+        set -o noglob
+        # Create a temporary logfile of all matches
+        find -L ${pictures} -iregex .*.jpg -o -iregex .*.png > ${tmp}
+        # reenable shell expansion
+        set +o noglob
+
+        # Choose a random line number (any number from 1 to the length of the file)
+        LowerBound=1
+        RandomMax=32767
+        UpperBound=$(cat ${tmp} | wc -l)
+        if [ $UpperBound -eq 0 ]
+        then
+            error "No matching pictures found."
+        fi
+        RandomLine=$(( $LowerBound + ($UpperBound * $RANDOM) / ($RandomMax + 1) ))
+
+        # Use sed to grab the random line
+        background=$(sed -n "$RandomLine{p;q;}" "${tmp}")
+    else # a file, should be a picture
+        background="${target}"
+    fi
+    background=`readlink -e "${background}"`
+}
+
+definebg() {
+    # set as default background
+    ln -nfs "${background}" "${defaultbg}"
+}
+
+displaybg() {
+    # set the background
     feh --no-fehbg --bg-fill ${defaultbg}
-fi
+}
 
-# show which picture is used
-echo `readlink --canonicalize ${background}`
+createlockpic() {
+    # create a picture fill-resized to the primary screen for the lockscreen
+    disp_res=`xrandr | grep primary | awk '{print $4}' | sed s/\+.*//g`
+    convert "${background}" -resize ${disp_res}^ \
+                            -gravity center \
+                            -extent ${disp_res} \
+                            "${lockscreen_image}"
+}
+
+showpath() {
+    # show which picture is used
+    echo `readlink --canonicalize ${background}`
+}
+
+main() {
+    case ${action} in
+        ## keep this in sync with options in checkcli
+        'lock')
+            pickpic
+            createlockpic
+            showpath
+            ;;
+        'redisplay') # just redisplay bg, adjusts new screen sizes
+            displaybg
+            ;;
+        'default')  # default action, pick and set a background
+            pickpic
+            definebg
+            displaybg
+            showpath
+            createlockpic
+            ;;
+        *)
+            error "Unknown action \"${action}\""
+            ;;
+    esac
+}
+
+
+## Main
+
+# what parameters did we get?
+checkcli
+
+# resolve target
+checktarget
+
+# action, and target are verified and set
+main
 
