mass update

diff --git a/bin/starship-upgrade b/bin/starship-upgrade
--- a/bin/starship-upgrade
+++ b/bin/starship-upgrade
@@ -15,13 +15,10 @@ source "$HOME/bin/common.bash"
 
 starship -V
 
-bash <(curl -fsSL https://starship.rs/install.sh) --verbose --bin-dir $HOMETMPDIR --yes
-if [ $? -eq 0 ]; then
-	mv -v $HOMETMPDIR/starship $HOME/bin2/starship
-else
-	echo "Error downloading startship to $HOMETMPDIR"
+bash <(curl -fsSL https://starship.rs/install.sh) --verbose --bin-dir $HOME/bin2 --yes
+if [ ! $? -eq 0 ]; then
+	echo "Error $? downloading startship to $HOMETMPDIR"
 fi
-
 
 starship -V
 
