Add screen detection to xdisp.

diff --git a/bin/xdisp b/bin/xdisp
--- a/bin/xdisp
+++ b/bin/xdisp
@@ -1,50 +1,71 @@
 #!/bin/bash
 
+checkmon() {
+    (echo -n "$DISPLAYS" | grep $1 | grep $2) 1>/dev/null 2>&1
+    return $?
+}
+
+action=$1
+DISPLAYS=`disper -l | sed ':a;N;s/\n/ /g'`
+
+echo -e "\n* Detected displays:\n"
+echo "$DISPLAYS"
+echo
+
 case $HOSTNAME in
     cyberlab)
         xrandr --output VGA-0 --mode 1680x1050
         xrandr --output VGA-0 --primary
         ;;
     goldorak)
-        if [ -z "$1" ] 
+        if [ -z "$action" ]
         then
-            action=laptop
-        else
-            action=$1
+            checkmon LVDS1 1366x768     ; laptop=$?
+            checkmon DP1 2560x1440      ; acdsamsung=$?
+            if [ $laptop -eq 0 -a $acdsamsung -eq 0 ]
+            then
+                action=acd
+                echo 'Detected ACD Samsung monitor, setting up dual screen.'
+            fi
         fi
         case $action in
-            lvds|lap*)
-                xrandr --output LVDS1 --mode 1366x768 --primary --pos 0x0
-                xrandr --output LVDS1 --primary
-        	    xrandr --output DP1 --off
-        	    xrandr --output VGA1 --off
-        	    xrandr --output HDMI1 --off
-        	    ;;
-            dp|acd)
-                xrandr --output DP1 --primary --mode 2560x1440 --pos 0x0 
-                xrandr --output LVDS1 --off
-                xrandr --output DP1 --primary --mode 2560x1440 --pos 0x0 --output LVDS1 --mode 1366x768 --noprimary --pos 2560x0
-                xrandr --output DP1 --primary
-        	    xrandr --output VGA1 --off
-        	    xrandr --output HDMI1 --off
-        	    ;;
+            ''|lap*)
+                xrandr --output LVDS1   --mode 1366x768 --primary --pos 0x0
+                xrandr --output LVDS1   --primary
+        	    xrandr --output DP1     --off
+        	    xrandr --output VGA1    --off
+        	    xrandr --output HDMI1   --off
+                ;;
         	vga)
-                xrandr --output LVDS1 --mode 1366x768 --primary --pos 0x0 --output VGA1 --auto --noprimary --pos 1366x0
-                xrandr --output LVDS1 --primary
-        	    xrandr --output DP1 --off
-        	    xrandr --output HDMI1 --off
+                xrandr --output LVDS1   --mode 1366x768 --primary --pos 0x0 \
+                       --output VGA1    --auto --noprimary --pos 1366x0
+                xrandr --output LVDS1   --primary
+        	    xrandr --output DP1     --off
+        	    xrandr --output HDMI1   --off
                 ;;
             proj*)
-                xrandr --output LVDS1 --auto --primary
-                xrandr --output VGA1  --auto --same-as LVDS1
-        	    xrandr --output DP1 --off
-        	    xrandr --output HDMI1 --off
+                xrandr --output LVDS1   --auto --primary
+                xrandr --output VGA1    --auto --same-as LVDS1
+        	    xrandr --output DP1     --off
+        	    xrandr --output HDMI1   --off
                 ;;
+            acd)
+                xrandr --output DP1     --primary --mode 2560x1440 --pos 0x0
+                xrandr --output LVDS1   --off
+                xrandr --output DP1     --primary --mode 2560x1440 --pos 0x0 \
+                       --output LVDS1   --mode 1366x768 --noprimary --pos 2560x0
+                xrandr --output DP1     --primary
+        	    xrandr --output VGA1    --off
+        	    xrandr --output HDMI1   --off
+        	    ;;
             *)
-                echo "$0 [acd|laptop|projector]"
+                echo -e "* ERROR: Invalid action $action\n"
                 exit 1
+                ;;
             esac
     esac
 
-# set background
-setbg
+echo -e "\n* Resetting / resizing background.\n"
+setbg >/dev/null
+echo
+
